import matplotlib.pyplot as plt

if __name__ == "__main__":



    # plt.figure(1)
    # plt.title('Near Field Diameter Stability')
    # plt.plot(nf['agitated']['diameter'], label='agitated')
    # plt.plot(nf['unagitated']['diameter'], label='unagitated')
    # plt.xlabel('Image number')
    # plt.ylabel('Diameter [um]')
    # plt.legend()

    # plt.figure(2)
    # plt.subplot(211)
    # plt.plot(nf['agitated']['center_x'], label='agitated')
    # plt.plot(nf['unagitated']['center_x'], label='unagitated')
    # plt.xlabel('Image number')
    # plt.ylabel('Position [um]')
    # plt.legend(title='Center X')
    # plt.title('Near Field Center Stability')
    # plt.subplot(212)
    # plt.plot(nf['agitated']['center_y'], label='agitated')
    # plt.plot(nf['unagitated']['center_y'], label='unagitated')
    # plt.xlabel('Image number')
    # plt.ylabel('Position [um]')
    # plt.legend(title='Center Y')

    # plt.figure(3)
    # plt.subplot(211)
    # plt.plot(nf['agitated']['centroid_x'], label='agitated')
    # plt.plot(nf['unagitated']['centroid_x'], label='unagitated')
    # plt.xlabel('Image number')
    # plt.ylabel('Position [um]')
    # plt.legend(title='Centroid X')
    # plt.title('Near Field Centroid Stability')
    # plt.subplot(212)
    # plt.plot(nf['agitated']['centroid_y'], label='agitated')
    # plt.plot(nf['unagitated']['centroid_y'], label='unagitated')
    # plt.xlabel('Image number')
    # plt.ylabel('Position [um]')
    # plt.legend(title='Centroid Y')

    # plt.figure(4)
    # plt.title('Far Field Diameter Stability')
    # plt.plot(ff['agitated']['diameter'], label='agitated')
    # plt.plot(ff['unagitated']['diameter'], label='unagitated')
    # plt.xlabel('Image number')
    # plt.ylabel('Diameter [um]')
    # plt.legend()

    # plt.figure(5)
    # plt.subplot(211)
    # plt.plot(ff['agitated']['center_x'], label='agitated')
    # plt.plot(ff['unagitated']['center_x'], label='unagitated')
    # plt.xlabel('Image number')
    # plt.ylabel('Position [um]')
    # plt.legend(title='Center X [um]')
    # plt.title('Far Field Center Stability')
    # plt.subplot(212)
    # plt.plot(ff['agitated']['center_y'], label='agitated')
    # plt.plot(ff['unagitated']['center_y'], label='unagitated')
    # plt.xlabel('Image number')
    # plt.ylabel('Position [um]')
    # plt.legend(title='Center Y [um]')

    # plt.figure(6)
    # plt.subplot(211)
    # plt.plot(ff['agitated']['centroid_x'], label='agitated')
    # plt.plot(ff['unagitated']['centroid_x'], label='unagitated')
    # plt.xlabel('Image number')
    # plt.ylabel('Position [um]')
    # plt.legend(title='Centroid X [um]')
    # plt.title('Far Field Centroid Stability')
    # plt.subplot(212)
    # plt.plot(ff['agitated']['centroid_y'], label='agitated')
    # plt.plot(ff['unagitated']['centroid_y'], label='unagitated')
    # plt.xlabel('Image number')
    # plt.ylabel('Position [um]')
    # plt.legend(title='Centroid Y [um]')

    # plt.show()
